language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 # - 5.4
 - 5.5
 - 5.6
 # - 7.0

matrix:
 allow_failures:
  - php: 7.0
  
env:
 global:
  - MOODLE_BRANCH=MOODLE_30_STABLE
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint || true
  - moodle-plugin-ci phpcpd || true
  - moodle-plugin-ci phpmd || true
  - moodle-plugin-ci codechecker || true
  - moodle-plugin-ci csslint || true
  - moodle-plugin-ci shifter || true
  - moodle-plugin-ci jshint || true
  - moodle-plugin-ci validate || true
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
